### ISSUE TITLE
BreakByTool and BreakByHand not working 1.16.1 and 1.16.2

### ISSUE THREAD

**Issue by Azagwen** [FabricMC/fabric#1044]
I was making my block registry class, and after adding loot tables to test if my blocks were dropping the right items with the right tools.

 I noticed that not only only were all of my blocks breakable with random tools, but ALSO that I could break them with my bare hands, despite specifying that I wanted them to break with Pickaxes of a specific Mininglevel

I asked for help on the Fabric discord, quite confused, nothing was wrong with my block registry class, so it seems that it's a bug ?
so when will this be fixed, or is it already being worked on ?

**Comment by Azagwen** [comment]
Note : still not working as expected in 1.16.2

**Comment by uiytt** [comment]
This is the same as #841 
Also, what version of fabric api do you use, since it should be solved since fabric api 0.16.1

**Comment by Azagwen** [comment]
> This is the same as #841
> Also, what version of fabric api do you use, since it should be solved since fabric api 0.16.1

I'm using version `0.19.0+build.398-1.16` for my 1.16.2 mod
and version `0.15.1+build.380-1.16.1` for my 1.16.1 mod

if I'm not mistaken `0.19.0+build.398-1.16` is the latest

**Comment by uiytt** [comment]
Yes it is so I can't help you...
But can you close this and report this in 841, it will allow the devs to have one issue with the report of everybody and not having duplicates of the same issue.

**Comment by Azagwen** [comment]
> Yes it is so I can't help you...
> But can you close this and report this in 841, it will allow the devs to have one issue with the report of everybody and not having duplicates of the same issue.

well you mentioned it in #841 so if I close it it can still be accessed from there 
I'm not sure of what I can add other than "it still doesn't work on `0.19.0+build.398-1.16`"
