### ISSUE TITLE
I'm currently using the latest version of Fabric and it runs smoothly without mods, I had a few errors but solved them and now I have these warns, I still crash though

### ISSUE THREAD

**Issue by RimuruT3mpest** [FabricMC/fabric#1480]
@Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
13:25:10.683
mixin
main
Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)
13:25:11.084
Hydrogen-Reflect
main
Trying to reflect-hack into the class-loader so we can define our own classes in an unrestricted loader...
13:25:11.084
Hydrogen-Reflect
main
** The JVM might warn you with something nasty! **

**Comment by Technici4n** [comment]
> @mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value

You can ignore this warning.

> Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)
13:25:11.084
Hydrogen-Reflect
main
Trying to reflect-hack into the class-loader so we can define our own classes in an unrestricted loader...
13:25:11.084
Hydrogen-Reflect
main
** The JVM might warn you with something nasty! **

Not sure these two are related, but if they are this looks like a Hydrogen issue that has got nothing to do with Fabric.

**Comment by RimuruT3mpest** [comment]
I deleted Hydrogen and am still crashing here are the remaining warns

@Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
14:40:24.604
Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)

They both have to do with Mixin

**Comment by RimuruT3mpest** [comment]
I fixed it on my own, if you ever have this issue here is a guide:
Open your launcher and go to Installations
Select the fabric version, click the 3 dots and press edit
Click Advanced options
Link your version of Java there, and example is:
C:\Program Files\Java\jdk-17\bin\java.exe
Save and enter
If you still get issues I can re open this to try to help.

**Comment by Technici4n** [comment]
Nice that you managed to fix it!

**Comment by RimuruT3mpest** [comment]
> Nice that you managed to fix it!

Thanks

**Comment by ranenvious** [comment]
How do you do this on GDlauncher? I have a 17.1 fabric instance but when I go to try to change the java path it always says java 16. I tried setting the path to java 17 but its still crashing so I assume I have to tell it that I am giving it 17 and not 16 but I can't see how.
